# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b2a8c2f6b3c6c4acd96093320663a6af5e1d0b4cae9c95bef65f65336a9a7c1d4bf875ba9b5274606033d3d2a262a47bee3c244182ae235c61bf86088b6ce15e

test:
  secret_key_base: 5bff5573255be46f283531930eb7455b1867ca65480fc3a7419e331310f3371fc137c0a1cf9c675baec1657e4083310169dfec2f3e278e3a4596c0207475c246

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
